name: removeWatermark-publish

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: 校验分支
        uses: actions/checkout@v3
        with:
          # 要校验的分支
          ref: main
          # 要获取的提交数。0表示所有分支和标记的所有历史记录。默认值：1
          fetch-depth: 0

      - name: 安装node环境
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - name: 安装依赖
        run: npm install

      - name: 打包文件
        run: npm run build

      - name: 推送到NPM上
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

